### ISSUE TITLE
Inconsistent naming of resource type directories

### ISSUE THREAD

**Issue by stilvoid** [aws-cloudformation/aws-cloudformation-samples#17]
Compare the following two paths:

`resource-types/awssamples-ec2-importkeypair/python/`
and
`resource-types/typescript-example-website-monitor/`

We should pick a strategy and stick to it while it's still early days for this repo. I prefer the first example `resource-types/{type name}/{language}/` :)

**Comment by stilvoid** [comment]
Additionally, we have an inconsistent naming scheme between modules and resource types.

Resource type directories are named the same as the resource type. Modules are not.

**Comment by mrinaudo-aws** [comment]
Thank you, @stilvoid - sorry for delays.  URLs may be actually referenced in other places already, so I think I'd be inclined in leaving them as they are at this point.

Closing this issue, feel free to reopen if needed.
