### ISSUE TITLE
Add Hook to enforce tagging requirements

### ISSUE THREAD

**Issue by bmorrissirromb** [aws-cloudformation/aws-cloudformation-samples#41]
I've developed a hook that will enforce tagging requirements and I think it would be a useful addition to this repo.

**Comment by maslick** [comment]
@bmorrissirromb please create a PR and reference it here

**Comment by bmorrissirromb** [comment]
Closing -- this has been better implemented in https://github.com/aws-cloudformation/aws-cloudformation-samples/tree/main/hooks/python-hooks/resource-tags
