### ISSUE TITLE
Custom Resource Type creation fails with Internal Failure

### ISSUE THREAD

**Issue by chamcca** [aws-cloudformation/aws-cloudformation-samples#87]
Working through the Workshop on creating Resource Types using the python and typescript examples in this repository, the Resource Types are registered successfully, but attempting to use them in a CloudFormation Stack always results in an Internal Failure.

I realize this isn't necessarily an issue with the samples, hoping to gain some insight on possible causes from the team given that these samples are assumed to function.

Additional Info:
- The `Internal Failure` appears to occur before the handler code is loaded or executed as it happens immediately and there are no CloudWatch Logs created
- I am able to locate and see (in CloudTrail) the AssumeRole that CloudFormation makes to the ExecutionRole created by the `cloudformation-cli`
- It was suggested on an internal thread that building/deploying the Resource Type from OSX may have caused an issue with the container image, so have shifted to building/deploying from CodeBuild
- This `Internal Failure` occurs on all Resource Types I have registered, even those created manually
- Bucket level ACLs are not allowed at the Org level for my accounts, so I am using a forked version of the `cloudformation-cli` based off of version 0.2.28 where I have removed the canned ACLs for the S3 Buckets created by the `CloudFormationManagedUploadInfrastructure` stack

**Comment by mrinaudo-aws** [comment]
Hi @chamcca - if you upgrade your copy of the CloudFormation CLI to the latest version at this time (`0.2.29`), and if you do the same for your copy of the `cloudformation-cli-python-plugin`,  do you still experience issues, or some of them?  For the latter, which specific issue do you see?

**Comment by chamcca** [comment]
upgrading to the new version of the cli (0.2.29) eliminated the need to use a forked version (the canned ACL appears to be removed from the LogsBucket in that stack). subsequent deployments of the python and typescript examples appear to be working this morning. I believe I am unblocked.
